name: 'Workflow Run Debounce TAC'
author: 'Srivishnu Kannappa'
description: 'Debounce multiple GitHub Actions Workflow Runs updated to node v20'
inputs:
  wait:
    description: 'Time to delay a GitHub Action. Always plan larger than you really need to defeat all GitHub API lags. Default to 5 minutes.'
    required: true
    default: '300'
  token:
    description: 'Personnal GitHub Access Token. Must have the `repo` scope '
    required: false
    default: ${{ github.token }}
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  color: yellow
  icon: pause-circle
